apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: genai-chat-spring-metal
  namespace: default
spec:
  alias: ai-chat
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: genai-chat
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: spring-metal

---
apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: genai-embed-spring-metal
  namespace: default
spec:
  alias: ai-embed
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: genai-embed
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: spring-metal
