apiVersion: v1
data:
  uri: aHR0cHM6Ly9nZW5haS1wcm94eS5zeXMudGFzLnZtdGFuenUuY29tCg==
  api-key: c2stU2RGQ2U4bHNRdUswcmRndndkZkNLUQo=
  model-name: bWV0YS1sbGFtYS9NZXRhLUxsYW1hLTMtOEItSW5zdHJ1Y3QK
  model-capabilities: Y2hhdAo=
  provider: dGFuenU= # tanzu
  type: Z2VuYWk=  # genai
kind: Secret
metadata:
  name: genai-chat-creds
type: servicebinding.io/ai

---
apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: genai-chat
spec:
  bindingConnectors:
  - name: main
    description: Gen AI credentials
    type: genai
    secretRef:
      name: genai-chat-creds
---
apiVersion: v1
data:
  uri: aHR0cHM6Ly9nZW5haS1wcm94eS5zeXMudGFzLnZtdGFuenUuY29tCg==
  api-key: c2stYTZ6TXY1T0tKTTlYQ3VBRGZFSVhMdwo=
  model-name: bm9taWMtZW1iZWQtdGV4dAo=
  model-capabilities: ZW1iZWRkaW5nCg==
  provider: dGFuenU= # tanzu
  type: Z2VuYWk=  # genai
kind: Secret
metadata:
  name: genai-embed-creds
type: servicebinding.io/ai

---
apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: genai-embed
spec:
  bindingConnectors:
  - name: main
    description: Gen AI credentials
    type: genai
    secretRef:
      name: genai-embed-creds
