apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: genai-service-bind
  namespace: default
spec:
  alias: ai
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: genai
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: pring-metal