apiVersion: v1
data:
  database: cG9zdGdyZXM= # postgres
  host: dGNwLnRhcy52bXRhbnp1LmNvbQo=
  username: cGdhZG1pbgo=
  password: clU0NjVGa0oxSDkzcTI3VkU4czAK
  port: MTAyNQo=
  provider: dGFzcG9zdGdyZXNxbA==  # tas
  type: cG9zdGdyZXNxbAo= # postgresql
kind: Secret
metadata:
  name: pgvector-creds
type: servicebinding.io/postgresql

---
apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: pgvector
spec:
  bindingConnectors:
  - name: main
    description: Posgres pgvector service for AI use cases
    type: postgresql
    secretRef:
      name: pgvector-creds
